FROM maven:3.9.9-eclipse-temurin-21 AS build

WORKDIR /workspace
COPY servicos /workspace/servicos
RUN mvn -f servicos/pom.xml -pl pos-graduacao -am -DskipTests package

FROM eclipse-temurin:21-jre

WORKDIR /app
COPY --from=build /workspace/servicos/pos-graduacao/target/*-SNAPSHOT.jar /app/app.jar
EXPOSE 8082
ENTRYPOINT ["java", "-jar", "/app/app.jar"]
