SET search_path TO diplomas;

CREATE TABLE IF NOT EXISTS pessoa (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  nome VARCHAR(150) NOT NULL,
  data_nascimento DATE NOT NULL,
  nome_social VARCHAR(150)
);

CREATE TABLE IF NOT EXISTS documento_identificacao (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  pessoa_id BIGINT NOT NULL UNIQUE REFERENCES pessoa(id),
  tipo VARCHAR(20) NOT NULL,
  numero VARCHAR(50) NOT NULL
);

CREATE TABLE IF NOT EXISTS contato (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  pessoa_id BIGINT NOT NULL REFERENCES pessoa(id),
  email VARCHAR(255),
  telefone VARCHAR(20)
);

CREATE TABLE IF NOT EXISTS endereco (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  pessoa_id BIGINT NOT NULL REFERENCES pessoa(id),
  logradouro VARCHAR(255) NOT NULL,
  cidade VARCHAR(120) NOT NULL,
  uf VARCHAR(2) NOT NULL,
  cep VARCHAR(10) NOT NULL
);

CREATE TABLE IF NOT EXISTS vinculo_academico (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  pessoa_id BIGINT NOT NULL REFERENCES pessoa(id),
  curso_id BIGINT,
  curso_codigo VARCHAR(50),
  curso_nome VARCHAR(150),
  curso_tipo VARCHAR(30),
  tipo_vinculo VARCHAR(30) NOT NULL,
  data_ingresso DATE NOT NULL,
  data_conclusao DATE,
  situacao VARCHAR(30) NOT NULL
);

-- Specific Tables
CREATE TABLE IF NOT EXISTS requerimento_diploma (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  pessoa_id BIGINT NOT NULL REFERENCES pessoa(id),
  vinculo_id BIGINT NOT NULL REFERENCES vinculo_academico(id),
  data_solicitacao DATE NOT NULL
);

CREATE TABLE IF NOT EXISTS base_emissao_diploma (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  requerimento_id BIGINT NOT NULL UNIQUE REFERENCES requerimento_diploma(id),
  pessoa_id BIGINT NOT NULL,
  pessoa_nome VARCHAR(150) NOT NULL,
  pessoa_nome_social VARCHAR(150),
  pessoa_data_nascimento DATE NOT NULL,
  curso_codigo VARCHAR(50) NOT NULL,
  curso_nome VARCHAR(150) NOT NULL,
  curso_tipo VARCHAR(30) NOT NULL,
  data_conclusao DATE NOT NULL,
  data_colacao_grau DATE
);

CREATE TABLE IF NOT EXISTS diploma (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  requerimento_id BIGINT NOT NULL UNIQUE REFERENCES requerimento_diploma(id),
  base_emissao_id BIGINT NOT NULL REFERENCES base_emissao_diploma(id),
  numero_registro VARCHAR(50) NOT NULL,
  data_emissao DATE NOT NULL
);

CREATE TABLE IF NOT EXISTS documento_diploma (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  diploma_id BIGINT NOT NULL REFERENCES diploma(id),
  versao INTEGER NOT NULL,
  data_geracao DATE NOT NULL,
  url_arquivo VARCHAR(255),
  hash_documento VARCHAR(255)
);

CREATE TABLE IF NOT EXISTS status_emissao (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  requerimento_id BIGINT NOT NULL UNIQUE REFERENCES requerimento_diploma(id),
  status VARCHAR(30) NOT NULL,
  data_atualizacao TIMESTAMP NOT NULL
);

-- View Helper
CREATE OR REPLACE VIEW vw_vinculo_academico_completo AS
SELECT
  v.id AS vinculo_id,
  v.pessoa_id,
  p.nome AS pessoa_nome,
  p.nome_social AS pessoa_nome_social,
  p.data_nascimento AS pessoa_data_nascimento,
  di.tipo AS documento_tipo,
  di.numero AS documento_numero,
  c.email AS contato_email,
  c.telefone AS contato_telefone,
  e.logradouro AS endereco_logradouro,
  e.cidade AS endereco_cidade,
  e.uf AS endereco_uf,
  e.cep AS endereco_cep,
  v.curso_id,
  v.curso_codigo,
  v.curso_nome,
  v.curso_tipo,
  v.tipo_vinculo,
  v.data_ingresso,
  v.data_conclusao,
  v.situacao
FROM vinculo_academico v
JOIN pessoa p ON p.id = v.pessoa_id
LEFT JOIN documento_identificacao di ON di.pessoa_id = p.id
LEFT JOIN LATERAL (
  SELECT c.email, c.telefone
  FROM contato c
  WHERE c.pessoa_id = p.id
  ORDER BY c.id
  LIMIT 1
) c ON true
LEFT JOIN LATERAL (
  SELECT e.logradouro, e.cidade, e.uf, e.cep
  FROM endereco e
  WHERE e.pessoa_id = p.id
  ORDER BY e.id
  LIMIT 1
) e ON true;

-- Outbox/Inbox for EDA
CREATE TABLE IF NOT EXISTS outbox_eventos (
  id UUID PRIMARY KEY,
  aggregate_id VARCHAR(255) NOT NULL,
  aggregate_type VARCHAR(255) NOT NULL,
  event_type VARCHAR(255) NOT NULL,
  payload JSONB NOT NULL,
  timestamp TIMESTAMP NOT NULL,
  version INTEGER
);

CREATE TABLE IF NOT EXISTS inbox_eventos (
  id UUID PRIMARY KEY,
  event_id UUID NOT NULL UNIQUE,
  aggregate_id VARCHAR(255) NOT NULL,
  event_type VARCHAR(255) NOT NULL,
  processed_at TIMESTAMP NOT NULL
);
