services:
  postgres:
    image: postgres:18
    restart: unless-stopped
    environment:
      POSTGRES_USER: ${POSTGRES_USER:-tcc}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:-tcc123}
      POSTGRES_DB: ${POSTGRES_DB:-tccdb}
      PGDATA: ${PGDATA:-/var/lib/postgresql/data/pgdata}
    ports:
      - "${POSTGRES_PORT:-5432}:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ../bd/${BD_CENARIO:-schemas}:/docker-entrypoint-initdb.d:ro
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U \"$$POSTGRES_USER\" -d \"$$POSTGRES_DB\""]
      interval: 10s
      timeout: 5s
      retries: 5
    networks:
      - tcc-network
