FROM maven:3.9.9-eclipse-temurin-21 AS build

WORKDIR /workspace
COPY servicos /workspace/servicos
RUN mvn -f servicos/pom.xml -pl graduacao -am -DskipTests package

FROM eclipse-temurin:21-jre

WORKDIR /app
COPY --from=build /workspace/servicos/graduacao/target/*-SNAPSHOT.jar /app/app.jar
EXPOSE 8081
ENTRYPOINT ["java", "-jar", "/app/app.jar"]
