CREATE TABLE IF NOT EXISTS curso_graduacao (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  codigo VARCHAR(50) NOT NULL UNIQUE,
  nome VARCHAR(255) NOT NULL,
  carga_horaria INTEGER NOT NULL
);

CREATE TABLE IF NOT EXISTS disciplina_graduacao (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  curso_id BIGINT NOT NULL REFERENCES curso_graduacao(id),
  codigo VARCHAR(20) NOT NULL,
  nome VARCHAR(255) NOT NULL,
  carga_horaria INTEGER NOT NULL
);

CREATE TABLE IF NOT EXISTS turma_graduacao (
  id VARCHAR(20) PRIMARY KEY,
  curso_id BIGINT NOT NULL REFERENCES curso_graduacao(id),
  ano INTEGER NOT NULL,
  semestre INTEGER NOT NULL,
  status VARCHAR(20) NOT NULL
);

CREATE TABLE IF NOT EXISTS pessoa (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  nome VARCHAR(150) NOT NULL,
  data_nascimento DATE NOT NULL,
  nome_social VARCHAR(150)
);

CREATE TABLE IF NOT EXISTS documento_identificacao (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  pessoa_id BIGINT NOT NULL UNIQUE REFERENCES pessoa(id),
  tipo VARCHAR(20) NOT NULL,
  numero VARCHAR(50) NOT NULL
);

CREATE TABLE IF NOT EXISTS contato (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  pessoa_id BIGINT NOT NULL REFERENCES pessoa(id),
  email VARCHAR(255),
  telefone VARCHAR(20)
);

CREATE TABLE IF NOT EXISTS endereco (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  pessoa_id BIGINT NOT NULL REFERENCES pessoa(id),
  logradouro VARCHAR(255) NOT NULL,
  cidade VARCHAR(120) NOT NULL,
  uf VARCHAR(2) NOT NULL,
  cep VARCHAR(10) NOT NULL
);

CREATE TABLE IF NOT EXISTS aluno_graduacao (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  turma_graduacao_id VARCHAR(20) NOT NULL REFERENCES turma_graduacao(id),
  pessoa_id BIGINT NOT NULL REFERENCES pessoa(id),
  data_matricula DATE NOT NULL,
  status VARCHAR(30) NOT NULL
);

CREATE TABLE IF NOT EXISTS professor_graduacao (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  curso_id BIGINT NOT NULL REFERENCES curso_graduacao(id),
  pessoa_id BIGINT NOT NULL REFERENCES pessoa(id),
  data_ingresso DATE NOT NULL,
  nivel_docente VARCHAR(30) NOT NULL,
  status VARCHAR(30) NOT NULL
);

CREATE TABLE IF NOT EXISTS vinculo_academico (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  pessoa_id BIGINT NOT NULL REFERENCES pessoa(id),
  curso_id BIGINT,
  curso_codigo VARCHAR(50),
  curso_nome VARCHAR(150),
  curso_tipo VARCHAR(30),
  tipo_vinculo VARCHAR(30) NOT NULL,
  data_ingresso DATE NOT NULL,
  data_conclusao DATE,
  situacao VARCHAR(30) NOT NULL
);

CREATE TABLE IF NOT EXISTS oferta_disciplina (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  disciplina_id BIGINT NOT NULL REFERENCES disciplina_graduacao(id),
  professor_id BIGINT NOT NULL REFERENCES professor_graduacao(id),
  ano INTEGER NOT NULL,
  semestre INTEGER NOT NULL
);

CREATE TABLE IF NOT EXISTS matricula_disciplina (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  aluno_id BIGINT NOT NULL REFERENCES aluno_graduacao(id),
  oferta_disciplina_id BIGINT NOT NULL REFERENCES oferta_disciplina(id),
  data_matricula DATE NOT NULL,
  status VARCHAR(20) NOT NULL,
  nota NUMERIC(4, 2)
);

CREATE TABLE IF NOT EXISTS avaliacao_oferta_disciplina (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  oferta_disciplina_id BIGINT NOT NULL REFERENCES oferta_disciplina(id),
  nome VARCHAR(100) NOT NULL,
  peso SMALLINT NOT NULL
);

CREATE TABLE IF NOT EXISTS avaliacao_aluno (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  matricula_id BIGINT NOT NULL REFERENCES matricula_disciplina(id),
  avaliacao_id BIGINT NOT NULL REFERENCES avaliacao_oferta_disciplina(id),
  nota NUMERIC(4, 2) NOT NULL
);
