CREATE TABLE IF NOT EXISTS curso_graduacao (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  codigo VARCHAR(50) NOT NULL UNIQUE,
  nome VARCHAR(255) NOT NULL,
  carga_horaria INTEGER NOT NULL
);

CREATE TABLE IF NOT EXISTS disciplina_graduacao (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  curso_id BIGINT NOT NULL REFERENCES curso_graduacao(id),
  codigo VARCHAR(20) NOT NULL,
  nome VARCHAR(255) NOT NULL,
  carga_horaria INTEGER NOT NULL
);

CREATE TABLE IF NOT EXISTS turma_graduacao (
  id VARCHAR(20) PRIMARY KEY,
  curso_id BIGINT NOT NULL REFERENCES curso_graduacao(id),
  ano INTEGER NOT NULL,
  semestre INTEGER NOT NULL,
  status VARCHAR(20) NOT NULL
);

CREATE TABLE IF NOT EXISTS pessoa (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  nome VARCHAR(150) NOT NULL,
  data_nascimento DATE NOT NULL,
  nome_social VARCHAR(150)
);

CREATE TABLE IF NOT EXISTS documento_identificacao (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  pessoa_id BIGINT NOT NULL UNIQUE REFERENCES pessoa(id),
  tipo VARCHAR(20) NOT NULL,
  numero VARCHAR(50) NOT NULL
);

CREATE TABLE IF NOT EXISTS contato (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  pessoa_id BIGINT NOT NULL REFERENCES pessoa(id),
  email VARCHAR(255),
  telefone VARCHAR(20)
);

CREATE TABLE IF NOT EXISTS endereco (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  pessoa_id BIGINT NOT NULL REFERENCES pessoa(id),
  logradouro VARCHAR(255) NOT NULL,
  cidade VARCHAR(120) NOT NULL,
  uf VARCHAR(2) NOT NULL,
  cep VARCHAR(10) NOT NULL
);

CREATE TABLE IF NOT EXISTS aluno_graduacao (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  turma_graduacao_id VARCHAR(20) NOT NULL REFERENCES turma_graduacao(id),
  pessoa_id BIGINT NOT NULL REFERENCES pessoa(id),
  data_matricula DATE NOT NULL,
  status VARCHAR(30) NOT NULL
);

CREATE TABLE IF NOT EXISTS professor_graduacao (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  curso_id BIGINT NOT NULL REFERENCES curso_graduacao(id),
  pessoa_id BIGINT NOT NULL REFERENCES pessoa(id),
  data_ingresso DATE NOT NULL,
  nivel_docente VARCHAR(30) NOT NULL,
  status VARCHAR(30) NOT NULL
);

CREATE TABLE IF NOT EXISTS vinculo_academico (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  pessoa_id BIGINT NOT NULL REFERENCES pessoa(id),
  curso_id BIGINT,
  curso_codigo VARCHAR(50),
  curso_nome VARCHAR(150),
  curso_tipo VARCHAR(30),
  tipo_vinculo VARCHAR(30) NOT NULL,
  data_ingresso DATE NOT NULL,
  data_conclusao DATE,
  situacao VARCHAR(30) NOT NULL
);

CREATE TABLE IF NOT EXISTS oferta_disciplina (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  disciplina_id BIGINT NOT NULL REFERENCES disciplina_graduacao(id),
  professor_id BIGINT NOT NULL REFERENCES professor_graduacao(id),
  ano INTEGER NOT NULL,
  semestre INTEGER NOT NULL
);

CREATE TABLE IF NOT EXISTS matricula_disciplina (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  aluno_id BIGINT NOT NULL REFERENCES aluno_graduacao(id),
  oferta_disciplina_id BIGINT NOT NULL REFERENCES oferta_disciplina(id),
  data_matricula DATE NOT NULL,
  status VARCHAR(20) NOT NULL,
  nota NUMERIC(4, 2)
);

CREATE TABLE IF NOT EXISTS avaliacao_oferta_disciplina (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  oferta_disciplina_id BIGINT NOT NULL REFERENCES oferta_disciplina(id),
  nome VARCHAR(100) NOT NULL,
  peso SMALLINT NOT NULL
);

CREATE TABLE IF NOT EXISTS avaliacao_aluno (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  matricula_id BIGINT NOT NULL REFERENCES matricula_disciplina(id),
  avaliacao_id BIGINT NOT NULL REFERENCES avaliacao_oferta_disciplina(id),
  nota NUMERIC(4, 2) NOT NULL
);

CREATE TABLE IF NOT EXISTS programa_pos (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  codigo VARCHAR(50) NOT NULL UNIQUE,
  nome VARCHAR(255) NOT NULL,
  carga_horaria INTEGER NOT NULL
);

CREATE TABLE IF NOT EXISTS disciplina_pos (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  programa_id BIGINT NOT NULL REFERENCES programa_pos(id),
  codigo VARCHAR(20) NOT NULL,
  nome VARCHAR(255) NOT NULL,
  carga_horaria INTEGER NOT NULL
);

CREATE TABLE IF NOT EXISTS professor_pos (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  programa_id BIGINT NOT NULL REFERENCES programa_pos(id),
  pessoa_id BIGINT NOT NULL REFERENCES pessoa(id),
  data_ingresso DATE NOT NULL,
  nivel_docente VARCHAR(30) NOT NULL,
  status VARCHAR(30) NOT NULL
);

CREATE TABLE IF NOT EXISTS aluno_pos_graduacao (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  programa_id BIGINT NOT NULL REFERENCES programa_pos(id),
  pessoa_id BIGINT NOT NULL REFERENCES pessoa(id),
  orientador_id BIGINT REFERENCES professor_pos(id),
  data_matricula DATE NOT NULL,
  status VARCHAR(30) NOT NULL
);

CREATE TABLE IF NOT EXISTS oferta_disciplina_pos (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  disciplina_id BIGINT NOT NULL REFERENCES disciplina_pos(id),
  professor_id BIGINT NOT NULL REFERENCES professor_pos(id),
  ano INTEGER NOT NULL,
  semestre INTEGER NOT NULL
);

CREATE TABLE IF NOT EXISTS matricula_disciplina_pos (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  aluno_id BIGINT NOT NULL REFERENCES aluno_pos_graduacao(id),
  oferta_disciplina_id BIGINT NOT NULL REFERENCES oferta_disciplina_pos(id),
  data_matricula DATE NOT NULL,
  status VARCHAR(20) NOT NULL,
  nota NUMERIC(4, 2)
);

CREATE TABLE IF NOT EXISTS defesa_pos (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  aluno_id BIGINT NOT NULL REFERENCES aluno_pos_graduacao(id),
  tipo VARCHAR(30) NOT NULL,
  nota NUMERIC(4, 2)
);

CREATE TABLE IF NOT EXISTS defesa_membro (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  defesa_id BIGINT NOT NULL REFERENCES defesa_pos(id),
  professor_id BIGINT NOT NULL REFERENCES professor_pos(id),
  nota NUMERIC(4, 2),
  presidente BOOLEAN NOT NULL
);

CREATE TABLE IF NOT EXISTS requerimento_diploma (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  pessoa_id BIGINT NOT NULL REFERENCES pessoa(id),
  vinculo_id BIGINT NOT NULL REFERENCES vinculo_academico(id),
  data_solicitacao DATE NOT NULL
);

CREATE TABLE IF NOT EXISTS base_emissao_diploma (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  requerimento_id BIGINT NOT NULL UNIQUE REFERENCES requerimento_diploma(id),
  pessoa_id BIGINT NOT NULL,
  pessoa_nome VARCHAR(150) NOT NULL,
  pessoa_nome_social VARCHAR(150),
  pessoa_data_nascimento DATE NOT NULL,
  curso_codigo VARCHAR(50) NOT NULL,
  curso_nome VARCHAR(150) NOT NULL,
  curso_tipo VARCHAR(30) NOT NULL,
  data_conclusao DATE NOT NULL,
  data_colacao_grau DATE
);

CREATE TABLE IF NOT EXISTS diploma (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  requerimento_id BIGINT NOT NULL UNIQUE REFERENCES requerimento_diploma(id),
  base_emissao_id BIGINT NOT NULL REFERENCES base_emissao_diploma(id),
  numero_registro VARCHAR(50) NOT NULL,
  data_emissao DATE NOT NULL
);

CREATE TABLE IF NOT EXISTS documento_diploma (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  diploma_id BIGINT NOT NULL REFERENCES diploma(id),
  versao INTEGER NOT NULL,
  data_geracao DATE NOT NULL,
  url_arquivo VARCHAR(255),
  hash_documento VARCHAR(255)
);

CREATE TABLE IF NOT EXISTS status_emissao (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  requerimento_id BIGINT NOT NULL UNIQUE REFERENCES requerimento_diploma(id),
  status VARCHAR(30) NOT NULL,
  data_atualizacao TIMESTAMP NOT NULL
);

CREATE TABLE IF NOT EXISTS usuario_assinante (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  pessoa_id BIGINT NOT NULL UNIQUE REFERENCES pessoa(id),
  email VARCHAR(255) NOT NULL,
  ativo BOOLEAN NOT NULL,
  data_cadastro DATE NOT NULL
);

CREATE TABLE IF NOT EXISTS documento_assinavel (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  documento_diploma_id BIGINT NOT NULL REFERENCES documento_diploma(id),
  descricao VARCHAR(255) NOT NULL,
  data_criacao TIMESTAMP NOT NULL
);

CREATE TABLE IF NOT EXISTS solicitacao_assinatura (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  documento_assinavel_id BIGINT NOT NULL REFERENCES documento_assinavel(id),
  status VARCHAR(30) NOT NULL,
  data_solicitacao TIMESTAMP NOT NULL,
  data_conclusao TIMESTAMP
);

CREATE TABLE IF NOT EXISTS assinatura (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  solicitacao_id BIGINT NOT NULL REFERENCES solicitacao_assinatura(id),
  usuario_assinante_id BIGINT NOT NULL REFERENCES usuario_assinante(id),
  status VARCHAR(30) NOT NULL,
  data_assinatura TIMESTAMP NOT NULL,
  motivo_recusa VARCHAR(255)
);

CREATE TABLE IF NOT EXISTS manifesto_assinatura (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  solicitacao_id BIGINT NOT NULL UNIQUE REFERENCES solicitacao_assinatura(id),
  auditoria VARCHAR(255) NOT NULL,
  carimbo_tempo TIMESTAMP NOT NULL,
  hash_final VARCHAR(255) NOT NULL
);
